src/main/java/com/application/jsf/IndexBean.java
package com.application.jsf;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import javax.annotation.PostConstruct;
import java.io.Serializable;

/**
 * User: kirill.salyamov
 * Time: 2016-05-06 18:13
 */
@Controller
@Scope("request")
public class IndexBean implements Serializable {

    @PostConstruct
    public void init() {
        System.out.println("hello");
    }

    public String getTitle() {
        return "HelloWorldPage";
    }

    public String getText() {
        return "HelloWorld";
    }
}

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<f:view xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:ng="http://xmlns.jcp.org/jsf/passthrough"
        xmlns:prime="http://primefaces.org/ui">
    <h:head>
        <meta charset="utf-8" />
        <title>#{indexBean.title}</title>
        <style>
            body {font-size:12px; }
        </style>
    </h:head>
    <h:body>
        <h:form>
            <prime:panel header="What do you see here?" >
                <div style="height: 50px">
                    This is a simple PrimeFaces 5 project running on Spring Boot
                </div>
            </prime:panel>
            <prime:panel header="JSF 2.2 Bean Access">
                #{indexBean.text}
            </prime:panel>
        </h:form>
    </h:body>
</f:view>